common/models/User.php
<?php
namespace common\models;

use backend\models\AuthAssignment;
use Yii;
use yii\base\NotSupportedException;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\web\IdentityInterface;

/**
 * User model
 *
 * @property integer $id
 * @property string $username
 * @property string $password_hash
 * @property string $password_reset_token
 * @property string $email
 * @property string $auth_key
 * @property integer $status
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $password write-only password
 */
class User extends ActiveRecord implements IdentityInterface
{
    const STATUS_DELETED = 0;
    const STATUS_ACTIVE = 10;


    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%user}}';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            ['status', 'default', 'value' => self::STATUS_ACTIVE],
            ['status', 'in', 'range' => [self::STATUS_ACTIVE, self::STATUS_DELETED]],

            ['username', 'trim'],
            ['username', 'required'],
            ['username', 'unique', 'targetClass' => '\common\models\User', 'message' => 'Этот логин уже зарегистрирован.'],
            ['username', 'string', 'min' => 2, 'max' => 255],

            ['email', 'trim'],
            ['email', 'required'],
            ['email', 'email'],
            ['email', 'string', 'max' => 255],
            ['email', 'unique', 'targetClass' => '\common\models\User', 'message' => 'Этот email уже зарегистрирован.'],
        ];
    }

    public function attributeLabels()
    {
        return [
            'username' => 'Логин',
        ];
    }

    public function getProfile()
    {
        return $this->hasOne(Profile::className(), ['user_id' => 'id']);
    }

    public function getRole()
    {
        return $this->hasOne(AuthAssignment::className(), ['user_id' => 'id']);
    }
    
    /**
     * @inheritdoc
     */
    public static function findIdentity($id)
    {
        return static::findOne(['id' => $id, 'status' => self::STATUS_ACTIVE]);
    }

    /**
     * @inheritdoc
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        throw new NotSupportedException('"findIdentityByAccessToken" is not implemented.');
    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        return static::findOne(['username' => $username, 'status' => self::STATUS_ACTIVE]);
    }

    /**
     * Finds user by password reset token
     *
     * @param string $token password reset token
     * @return static|null
     */
    public static function findByPasswordResetToken($token)
    {
        if (!static::isPasswordResetTokenValid($token)) {
            return null;
        }

        return static::findOne([
            'password_reset_token' => $token,
            'status' => self::STATUS_ACTIVE,
        ]);
    }

    /**
     * Finds out if password reset token is valid
     *
     * @param string $token password reset token
     * @return bool
     */
    public static function isPasswordResetTokenValid($token)
    {
        if (empty($token)) {
            return false;
        }

        $timestamp = (int) substr($token, strrpos($token, '_') + 1);
        $expire = Yii::$app->params['user.passwordResetTokenExpire'];
        return $timestamp + $expire >= time();
    }

    /**
     * @inheritdoc
     */
    public function getId()
    {
        return $this->getPrimaryKey();
    }

    /**
     * @inheritdoc
     */
    public function getAuthKey()
    {
        return $this->auth_key;
    }

    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey)
    {
        return $this->getAuthKey() === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return bool if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return Yii::$app->security->validatePassword($password, $this->password_hash);
    }

    /**
     * Generates password hash from password and sets it to the model
     *
     * @param string $password
     */
    public function setPassword($password)
    {
        $this->password_hash = Yii::$app->security->generatePasswordHash($password);
    }

    /**
     * Generates "remember me" authentication key
     */
    public function generateAuthKey()
    {
        $this->auth_key = Yii::$app->security->generateRandomString();
    }

    /**
     * Generates new password reset token
     */
    public function generatePasswordResetToken()
    {
        $this->password_reset_token = Yii::$app->security->generateRandomString() . '_' . time();
    }

    /**
     * Removes password reset token
     */
    public function removePasswordResetToken()
    {
        $this->password_reset_token = null;
    }
}

backend/views/layouts/_menu.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;

$bc_badge = Yii::$app->badges->backCallBadge()
?>

<div class="sidebar-content">

    <div class="sidebar-user-material">
        <div class="category-content">
            <div class="sidebar-user-material-content">
                <a class="legitRipple" href="#"><img src="<?= isset($profile) ? $profile->avatar : '/web/images/placeholder.jpg' ?>" class="img-circle img-responsive" alt="profile_image"></a>
                <h6><?= isset($profile) ? $profile->surname.' '.$profile->name : 'Пользователь' ?></h6>
            </div>
        </div>
    </div>

    <div class="sidebar-category sidebar-category-visible">
        <div class="category-content no-padding">
            <ul class="navigation navigation-main navigation-accordion">
                <li class="navigation-header"><span>Меню</span> <i class="icon-menu" title="Main pages"></i></li>
                <li <?= Yii::$app->controller->id == 'dashboard' ? 'class="active"' : '' ?> ><a class="pjax-link" href="<?= Url::to(['/site/index']) ?>"><i class="icon-home4"></i> <span>Главная</span></a></li>
                <li <?= Yii::$app->controller->id == 'back-call' ? 'class="active"' : '' ?> >
                    <a class="pjax-link" href="<?= Url::to(['/back-call/index']) ?>">
                        <i class="icon-phone"></i>
                        <span>Обратный звонок
                            <?= $bc_badge != 0 ? '<span class="badge bg-teal-400 pull-right">'.$bc_badge.'</span>' : '' ?>
                        </span>
                    </a>
                </li>
                <li <?= Yii::$app->controller->id == 'staff' ? 'class="active"' : '' ?> ><a class="pjax-link" href="<?= Url::to(['/staff/index']) ?>"><i class="icon-users2"></i> <span>Персонал</span></a></li>
                <li <?= Yii::$app->controller->id == 'category' ? 'class="active"' : '' ?> ><a class="pjax-link" href="<?= Url::to(['/category/index']) ?>"><i class="icon-price-tag2"></i> <span>Категории</span></a></li>
                <li <?= Yii::$app->controller->id == 'products' ? 'class="active"' : '' ?> ><a class="pjax-link" href="<?= Url::to(['/products/index']) ?>"><i class="icon-box"></i> <span>Блюда</span></a></li>
                <li <?= Yii::$app->controller->id == 'recommend-products' ? 'class="active"' : '' ?> ><a href="<?= Url::to(['/recommend-products/index']) ?>"><i class="icon-thumbs-up2"></i> <span>Рекомендуемые блюда</span></a></li>
                <li>
                    <a class="pjax-link" href="#"><i class="icon-cog5"></i> <span>Настройки сайта</span></a>
                    <ul>
                        <li><a href="<?= Url::to(['/site-settings/index']) ?>">Главная страница</a></li>
                        <li><a class="pjax-link" href="<?= Url::to(['/site-settings/address']) ?>">Адреса и телефоны</a></li>
                        <li><a class="pjax-link" href="<?= Url::to(['/city-area/index']) ?>">Районы доставки</a></li>
                        <li><a class="pjax-link" href="<?= Url::to(['/site-settings/score']) ?>">Система баллов</a></li>
                        <li><a href="<?= Url::to(['/site-settings/payment-system']) ?>">Платежная система</a></li>
                        <li><a class="pjax-link" href="<?= Url::to(['/site-settings/main-seo']) ?>">SEO</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>

</div>

backend/views/layouts/_top_menu.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use common\models\SiteSettings;

$settings = SiteSettings::findOne(1);
?>

<div class="navbar-header">
<!--    <a class="navbar-brand" href="--><?//= Url::to(['/dashboard/index']) ?><!--"><img src="/backend/web/images/logo_light.png" alt=""></a>-->
    <a class="navbar-brand" href="<?= Url::to(['/dashboard/index']) ?>"><?= $settings->name ?></a>

    <ul class="nav navbar-nav visible-xs-block">
        <li><a data-toggle="collapse" data-target="#navbar-mobile"><i class="icon-tree5"></i></a></li>
        <li><a class="sidebar-mobile-main-toggle"><i class="icon-paragraph-justify3"></i></a></li>
    </ul>
</div>

<div class="navbar-collapse collapse" id="navbar-mobile">
    <ul class="nav navbar-nav">
        <li><a class="sidebar-control sidebar-main-toggle hidden-xs"><i class="icon-paragraph-justify3"></i></a></li>
    </ul>

    <div class="navbar-right">
        <p class="navbar-text">Здравствуйте, <?= isset($profile) ? $profile->name : 'Пользователь' ?>!</p>

        <ul class="nav navbar-nav">
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <i class="icon-bell2"></i>
                    <span class="visible-xs-inline-block position-right">Activity</span>
                    <span class="status-mark border-pink-300"></span>
                </a>

                <div class="dropdown-menu dropdown-content">
                    <div class="dropdown-content-heading">
                        Activity
                        <ul class="icons-list">
                            <li><a href="#"><i class="icon-menu7"></i></a></li>
                        </ul>
                    </div>

                    <ul class="media-list dropdown-content-body width-350">
                        <li class="media">
                            <div class="media-left">
                                <a href="#" class="btn bg-success-400 btn-rounded btn-icon btn-xs"><i class="icon-mention"></i></a>
                            </div>

                            <div class="media-body">
                                <a href="#">Taylor Swift</a> mentioned you in a post "Angular JS. Tips and tricks"
                                <div class="media-annotation">4 minutes ago</div>
                            </div>
                        </li>

                        <li class="media">
                            <div class="media-left">
                                <a href="#" class="btn bg-pink-400 btn-rounded btn-icon btn-xs"><i class="icon-paperplane"></i></a>
                            </div>

                            <div class="media-body">
                                Special offers have been sent to subscribed users by <a href="#">Donna Gordon</a>
                                <div class="media-annotation">36 minutes ago</div>
                            </div>
                        </li>

                        <li class="media">
                            <div class="media-left">
                                <a href="#" class="btn bg-blue btn-rounded btn-icon btn-xs"><i class="icon-plus3"></i></a>
                            </div>

                            <div class="media-body">
                                <a href="#">Chris Arney</a> created a new <span class="text-semibold">Design</span> branch in <span class="text-semibold">Limitless</span> repository
                                <div class="media-annotation">2 hours ago</div>
                            </div>
                        </li>

                        <li class="media">
                            <div class="media-left">
                                <a href="#" class="btn bg-purple-300 btn-rounded btn-icon btn-xs"><i class="icon-truck"></i></a>
                            </div>

                            <div class="media-body">
                                Shipping cost to the Netherlands has been reduced, database updated
                                <div class="media-annotation">Feb 8, 11:30</div>
                            </div>
                        </li>

                        <li class="media">
                            <div class="media-left">
                                <a href="#" class="btn bg-warning-400 btn-rounded btn-icon btn-xs"><i class="icon-bubble8"></i></a>
                            </div>

                            <div class="media-body">
                                New review received on <a href="#">Server side integration</a> services
                                <div class="media-annotation">Feb 2, 10:20</div>
                            </div>
                        </li>

                        <li class="media">
                            <div class="media-left">
                                <a href="#" class="btn bg-teal-400 btn-rounded btn-icon btn-xs"><i class="icon-spinner11"></i></a>
                            </div>

                            <div class="media-body">
                                <strong>January, 2016</strong> - 1320 new users, 3284 orders, $49,390 revenue
                                <div class="media-annotation">Feb 1, 05:46</div>
                            </div>
                        </li>
                    </ul>
                </div>
            </li>

            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <i class="icon-profile"></i>
                </a>

                <div class="dropdown-menu dropdown-content">
                    <div class="dropdown-content-heading">
                        Мой аккаунт (<?= Yii::$app->user->identity->role->item_name ?>)
                    </div>

                    <ul class="media-list dropdown-content-body width-350">
                        <li class="media">
                            <div class="media-left">
                                <a href="#" class="btn bg-success-400 btn-rounded btn-icon btn-xs"><i class="icon-reading"></i></a>
                            </div>

                            <div class="media-body">
                                <a href="<?= Url::to(['/site/profile']) ?>"><span>Мой профиль</span></a>
                            </div>
                        </li>

                        <li class="media">
                            <div class="media-left">
                                <a href="#" class="btn bg-success-400 btn-rounded btn-icon btn-xs"><i class="icon-key"></i></a>
                            </div>

                            <div class="media-body">
                                <a href="<?= Url::to(['/site/change-password']) ?>"><span>Смена пароля</span></a>
                            </div>
                        </li>

                        <li class="media">
                            <div class="media-left">
                                <a href="#" class="btn bg-success-400 btn-rounded btn-icon btn-xs"><i class="icon-exit3"></i></a>
                            </div>

                            <div class="media-body">
                                <?= Html::a('<span>Выход</span>',
                                    ['/site/logout'],
                                    [
                                        'data' => [
                                            'method' => 'post'
                                        ]
                                ]) ?>
                            </div>
                        </li>
                    </ul>
                </div>
            </li>

        </ul>
    </div>
</div>

backend/views/layouts/login.php
<?php

use backend\assets\AppAsset;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use common\widgets\Alert;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body class="login-container">
<?php $this->beginBody() ?>

<div class="page-container">
    <div class="page-content">
        <div class="content-wrapper">
            <div class="content">

                <?= Alert::widget() ?>
                <?= $content ?>
                
                <div class="footer text-muted text-center">
                    &copy; <?= date('Y') ?>. BBQ
                </div>

            </div>
        </div>
    </div>
</div>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

backend/views/layouts/main.php
<?php

use yii\helpers\Html;
use yii\widgets\Pjax;
use common\widgets\Alert;
use backend\assets\AppAsset;
use common\models\Profile;

$profile = Profile::findOne(['user_id' => Yii::$app->user->getId()]);

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="navbar navbar-default header-highlight pjax-load">
    <?= $this->render('_top_menu', [
        'profile' => $profile
    ]) ?>
</div>


<div class="page-container">
    <?php Pjax::begin([
        'id' => 'dynamic-pjax',
        'formSelector' => '.pjax-load',
        'linkSelector' => '.pjax-link',
        'options' => [
            'class' => 'page-content'
        ]
    ]) ?>
        <div id="pjax-load" class="sidebar sidebar-main pjax-load">
            <?= $this->render('_menu', [
                'profile' => $profile
            ]) ?>
        </div>

        <div class="content-wrapper">
            <div class="content pjax-load">
                <?= Alert::widget() ?>
                <?= $content ?>
            </div>
        </div>
    <?php Pjax::end() ?>
</div>


<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>